### ISSUE TITLE
Eye On Water Integration Issue

### ISSUE THREAD

**Issue by zacharyasmith** [kdeyev/pyonwater#20]
I think this is a bug for this repo actually.

https://github.com/kdeyev/eyeonwater/issues/104

**Comment by kdeyev** [comment]
Hi @zacharyasmith 
Thank you for reporting the issue.
Based on the error message it seem that the JSON payload does not meet the [data model requirements](https://github.com/kdeyev/pyonwater/blob/main/pyonwater/models/eow_historical_models.py#L75C1-L76C21).
```
pyonwater.exceptions.EyeOnWaterAPIError: Unexpected EOW response 2 validation errors for HistoricalData
timeseries -> 4928193028058372026,0 -> series -> 9 -> display_unit
  field required (type=value_error.missing)
timeseries -> 4928193028058372026,0 -> series -> 9 -> bill_read
  field required (type=value_error.missing)
  ```
The eow api is close and not documented, and I'm doing my best with the reverse engineering here. 
It would be very helpful if you could run the [example.py]https://github.com/kdeyev/pyonwater/blob/main/example.py and grab the actual response coming from eyeonwater.com.

**Comment by zacharyasmith** [comment]
@kdeyev I ran it with success. There were no errors with pydantic. I won't share it without redaction here.

**Comment by kdeyev** [comment]
If there is no errors, everything is fine and there is no reason to share.
I wonder why it does not work in the HA integration. Could you please try to request 30-90 days of statistics?

**Comment by zacharyasmith** [comment]
With 30 days of data called. The log is the raw json redacted.

```
Traceback (most recent call last):
  File "pyonwater/pyonwater/meter_reader.py", line 115, in read_historical_data_one_day
    data = HistoricalData.parse_raw(raw_data)
  File "pydantic/main.py", line 549, in pydantic.main.BaseModel.parse_raw
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for HistoricalData
timeseries -> 4928193028058372026,0 -> series -> 9 -> display_unit
  field required (type=value_error.missing)
timeseries -> 4928193028058372026,0 -> series -> 9 -> bill_read
  field required (type=value_error.missing)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pyonwater/example.py", line 46, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "pyonwater/example.py", line 38, in main
    await meter.read_historical_data(client=client, days_to_load=30)
  File "pyonwater/pyonwater/meter.py", line 64, in read_historical_data
    historical_data = await self._reader.read_historical_data(
  File "pyonwater/pyonwater/meter_reader.py", line 79, in read_historical_data
    statistics += await self.read_historical_data_one_day(
  File "pyonwater/pyonwater/meter_reader.py", line 119, in read_historical_data_one_day
    raise EyeOnWaterAPIError(msg) from e
pyonwater.exceptions.EyeOnWaterAPIError: Unexpected EOW response 2 validation errors for HistoricalData
timeseries -> 4928193028058372026,0 -> series -> 9 -> display_unit
  field required (type=value_error.missing)
timeseries -> 4928193028058372026,0 -> series -> 9 -> bill_read
  field required (type=value_error.missing)
```

[data.log](https://github.com/kdeyev/pyonwater/files/14806354/data.log)

**Comment by zacharyasmith** [comment]
Looks like the  `display_unit` and `bill_read` is not a guaranteed field.

https://github.com/kdeyev/pyonwater/blob/39e8faa69b41e3d379f8141b166564f635513b9f/pyonwater/models/eow_historical_models.py#L75

**Comment by zacharyasmith** [comment]
Possible fix for you. It at least removes the Exception raises.

```diff
diff --git a/pyonwater/meter.py b/pyonwater/meter.py
index 456331f..b070924 100644
--- a/pyonwater/meter.py
+++ b/pyonwater/meter.py
@@ -65,7 +65,7 @@ class Meter:
             client=client, days_to_load=days_to_load
         )

-        historical_data = [self._convert_to_native(dp) for dp in historical_data if dp.unit is not None]
+        historical_data = [self._convert_to_native(dp) for dp in historical_data]

         if not self.last_historical_data:
             self.last_historical_data = historical_data
diff --git a/pyonwater/models/eow_historical_models.py b/pyonwater/models/eow_historical_models.py
index be37db2..d252b7f 100644
--- a/pyonwater/models/eow_historical_models.py
+++ b/pyonwater/models/eow_historical_models.py
@@ -72,8 +72,8 @@ class Params(BaseModel):
 class Series(BaseModel):
     # Mandatory fields
     date: datetime
-    display_unit: Optional[EOWUnits]
-    bill_read: Optional[float]
+    display_unit: EOWUnits
+    bill_read: float

     # Optional fields
     end_date: Optional[datetime] = None
```

**Comment by kdeyev** [comment]
@zacharyasmith it makes sense.
Could you please share how the time series looks like? (it probably will not require the PI reduction)
I wonder why did they add an empty point to the time series. 
Or may be they use an alternative payload format (I saw it before), then we can probably make a better fix. 
Thank you again for the collaboration!

**Comment by zacharyasmith** [comment]
I attached it in this comment earlier:
https://github.com/kdeyev/pyonwater/issues/20#issuecomment-2027453599

**Comment by kdeyev** [comment]
My bad. 
I see, you have a brand new meter. Now it makes sense

**Comment by kdeyev** [comment]
should be fixed here: https://github.com/kdeyev/pyonwater/releases/tag/v0.3.9

**Comment by zacharyasmith** [comment]
Nice work on the project. Thanks for the quick support today.
